{
 "title": "Adonis",
 "description": "My Adonis Monitoring",
 "tags": [ "adonis" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(nodejs_version_info, instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Requests by second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(adonis_throughput_metrics[1m])"
    }
   ]
  },
  {
   "title": "Request volume rate by url",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (url) (rate(adonis_http_request_durations_count[1m]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(adonis_http_request_durations_sum[5m]) / rate(adonis_http_request_durations_count[5m]))"
    }
   ]
  },
  {
   "title": "Response error rate by URL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "sum by (statusCode, url, method) (rate(adonis_http_request_durations_count[5m]))",
     "legendFormat": "{{ method }} {{ url }} - {{ statusCode }}"
    }
   ]
  }
 ]
}