name: checks

on:
  - push
  - pull_request

jobs:
  lint:
    uses: julien-r44/.github/.github/workflows/lint.yml@main

  typecheck:
    uses: julien-r44/.github/.github/workflows/typecheck.yml@main

  test:
    uses: julien-r44/.github/.github/workflows/test.yml@main
